image:
- Visual Studio 2019

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: /vAqj/nAkorMNahSdPaw87qExCfPoD0jvWCKE3rGMndVth55ovxVhPhQiLzkCWgYcBbGxKXSy84WuxhKQI+3WQJ/xeVcYRzy50j4f5TKN2nKZrIRlxUPSnwNfiXyCGYX
  APPVEYOR_REPO_TAG: true
  APPVEYOR_REPO_TAG_NAME: "1.0.0"

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name "Proyects Manager" --icon assets\proyectManager.ico --product-name ProyectManager --product-version "1.0.0"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    APPVEYOR_REPO_TAG: true
#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a proyect-manager-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: dist\proyect-manager-windows.zip
